Vectors, matrices, and tensors can be created and manipulated in Python. One of the most
prominent Python packages used for linear algebra is NumPy. The following code snippet
shows how vectors, matrices, and tensors can be created using NumPy:

In [ ]:
import numpy as np
x = np.array([1,2,3]) # a vector with three components.
y = np.array([4,5,6]) # another vector.
A = np.array([[1,2,3], [4,5,6], [7,5,6]]) # a 3x3 matrix.
B = np.array([[2,3,4], [1,2,0], [3,3,3]]) # another 3x3 matrix.
v = np.kron(x,A) # a tensor product of vector x and matrix A.
print(v)
w = np.kron(y,B) # a tensor product of vector y and matrix B.
print(w)

[[ 1  2  3  2  4  6  3  6  9]
 [ 4  5  6  8 10 12 12 15 18]
 [ 7  5  6 14 10 12 21 15 18]]
[[ 8 12 16 10 15 20 12 18 24]
 [ 4  8  0  5 10  0  6 12  0]
 [12 12 12 15 15 15 18 18 18]]


The preceding code snippet can be explained as follows:
1. First, numpy is imported using the alias np.
2. Then, two vectors, x and y, are created using the array() function from numpy.
3. This is followed by the creation of two matrices, A and B.
4. Finally, two tensor products, v and w, are created using the kron() function from
numpy.
The former (tensor product v) is the tensor product of vector x and matrix A, while
the latter (tensor product w) is the tensor product of vector y and matrix B.
Arithmetic operations, such as addition, subtraction, and scalar multiplication, can be
performed on the vectors. The same is also true of matrices and tensors. The following
code snippet shows some examples of arithmetic operations on vectors, matrices, and
tensors:

In [ ]:
# Arithmetic operations
#vectors
z1 = x + y # vector addition
print(z1)
z2 = x - y # vector subtraction
print(z2)
z3 = 2 * z1 # scalar multiplication
print(z3)
#matrices
C1 = A * B # matrix multiplication
print(C1)
C2 = x * A # a product of a vector and a matrix
print(C2)
#tensors
u = v + w # tensor addition
print(u)
u1 = 5 * u # multiplication of a tensor by a scalar
print(u1)

[5 7 9]
[-3 -3 -3]
[10 14 18]
[[ 2  6 12]
 [ 4 10  0]
 [21 15 18]]
[[ 1  4  9]
 [ 4 10 18]
 [ 7 10 18]]
[[ 9 14 19 12 19 26 15 24 33]
 [ 8 13  6 13 20 12 18 27 18]
 [19 17 18 29 25 27 39 33 36]]
[[ 45  70  95  60  95 130  75 120 165]
 [ 40  65  30  65 100  60  90 135  90]
 [ 95  85  90 145 125 135 195 165 180]]


The output of a dot product is a scalar. The Python code for computing an inner
product for two vectors using numpy is as follows:

In [ ]:
import numpy as np
x = np.array([1,2,3]) # a vector with three components.
y = np.array([4,5,6]) # another vector.
# The output of an inner product of vectors is a scalar
a = np.inner(x,y)
print(a)

32


The preceding code snippet imports numpy (using the alias np). Then it creates two
vectors, x and y. Finally, the inner product of these two vectors is calculated using
the inner() function from numpy. The Python code snippet
for computing an outer product of two vectors is shown as follows:

In [ ]:
import numpy as np
x = np.array([1,2,3]) # a vector with three components.
y = np.array([4,5,6]) # another vector.
# The output of an outer product of vectors is a matrix
a = np.outer(x,y)
print(a)

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


This code uses numpy to create two vectors, x and y. Then it uses the outer()
function from numpy in order to compute the outer product of vectors x and y.

The Python code snippet for computing the determinant of a matrix is given as
follows:

In [ ]:
import numpy as np
A = np.array([[1,2,3], [4,5,6], [1,5,1]]) # a 3x3 matrix.
det_A = np.linalg.det(A)
print(det_A)

24.000000000000004


The preceding code uses the linalg.det() function from numpy in order to
compute the determinant of the matrix A.

A Python code for a matrix transpose is shown as follows, using numpy:

In [ ]:
A1=np.transpose(A)
print(A1)

[[1 4 1]
 [2 5 5]
 [3 6 1]]


The preceding code uses the transpose() function from numpy in order to
compute the transpose of the matrix A.

The calculation of the eigenvalues and eigenvectors in Python is fairly easy. The main built-in function in Python to solve the eigenvalue/eigenvector problem for a square array is the eig function in numpy.linalg. Let’s see how we can use it.

In [ ]:
import numpy as np
from numpy.linalg import eig

a = np.array([[0, 2], 
              [2, 3]])
w,v=eig(a)
print('E-value:', w)
print('E-vector', v)

E-value: [-1.  4.]
E-vector [[-0.89442719 -0.4472136 ]
 [ 0.4472136  -0.89442719]]


In [ ]:
a = np.array([[2, 2, 4], 
              [1, 3, 5],
              [2, 3, 4]])
w,v=eig(a)
print('E-value:', w)
print('E-vector', v)

E-value: [ 8.80916362  0.92620912 -0.73537273]
E-vector [[-0.52799324 -0.77557092 -0.36272811]
 [-0.604391    0.62277013 -0.7103262 ]
 [-0.59660259 -0.10318482  0.60321224]]


In [ ]:
!pip install qutip
from qutip import *
import numpy as np
A = np.array([[2,3], [4,5]])
B = np.array([[2,4], [1,0]])
A = Qobj(A); B = Qobj(B)
# computing tensor product using qutip
C = tensor(A,B); print(C)
#computing tensor product using numpy
D = np.kron(A,B); print(D)

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 55.0 MB/s eta 0:00:00
Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[ 4.  8.  6. 12.]
 [ 2.  0.  3.  0.]
 [ 8. 16. 10. 20.]
 [ 4.  0.  5.  0.]]
[[ 4.+0.j  8.+0.j  6.+0.j 12.+0.j]
 [ 2.+0.j  0.+0.j  3.+0.j  0.+0.j]
 [ 8.+0.j 16.+0.j 10.+0.j 20.+0.j]
 [ 4.+0.j  0.+0.j  5.+0.j  0.+0.j]]


The code uses two modules, namely, qutip and numpy. First, two matrices A and B are
created using numpy. These matrices are also converted into qutip objects by using the
Qobj() function. Then, the tensor product is computed using both qutip and numpy.
For the former, the tensor() function is used, while for the latter, the kron() function
is used.

In [ ]:
from qutip import *
import numpy as np
A = np.array([[2,3], [4,5]])
B = np.array([[2,4], [1,1]])
# convert the arrays A and B to qutip objects
A = Qobj(A); B = Qobj(B)
T = tensor(A,B);
print("The tensor product is", T)
print("The trace of T is", T.tr())
Tr_B = T.ptrace(0) # trace out B by selecting A; thus A Tr(B)
print("Tr_B is", Tr_B)
Tr_A = T.ptrace(1) # trace out A by selecting B; thus B Tr(A)
print("Tr_A is", Tr_A)

The tensor product is Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[ 4.  8.  6. 12.]
 [ 2.  2.  3.  3.]
 [ 8. 16. 10. 20.]
 [ 4.  4.  5.  5.]]
The trace of T is 21.0
Tr_B is Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[ 6.  9.]
 [12. 15.]]
Tr_A is Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[14. 28.]
 [ 7.  7.]]


The code uses two Python modules, qutip and numpy. First, two matrices, A and B,
are created using numpy. Then, these matrices are converted into qutip objects. This is
followed by computing the tensor product of matrices A and B, and this tensor product
is assigned to T. Then, the trace of T is computed using the tr() function from qutip.
Finally, using the ptrace() function from qutip, the partial trace is computed.

The Python code for implementing the X gate in Python using numpy and qutip is
shown here:

In [ ]:
!pip install qutip
from qutip import *
import numpy as np
A = np.array([[1], [0]])
B = np.array([[0], [1]])
Rho_x = sigmax()
A = Qobj(A)
B = Qobj(B)
C = Rho_x * A
print(C)
D = Rho_x * B
print(D)

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]
Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]


The preceding code uses qutip and numpy. Then, two vectors A and B are created using
the array() function from numpy. Then, a new variable called Rho_x is assigned to
the X gate using the sigmax() function from qutip. Finally, two variables, C and D, are
assigned to the product of Rho_x and A, and the product of Rho_x and B. The variable C
is equivalent to applying the X gate to A, while D is equivalent to applying the X gate to B.

The Python code for implementing a Z gate is shown as follows:

In [ ]:
from qutip import *
import numpy as np
A = np.array([[1], [0]])
B = np.array([[0], [1]])
Rho_z = sigmaz()
A = Qobj(A)
B = Qobj(B)
C = Rho_z * A
D = Rho_z * B
print(C)
print(D)

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]
Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[ 0.]
 [-1.]]


The preceding code snippet uses the qutip and numpy Python modules to demonstrate
the application of the Z gate to two vectors, A and B, and the results of these operations are
given as C and D, respectively.

The Python code for implementing a Y gate is shown as follows:

In [ ]:
from qutip import *
import numpy as np
A = np.array([[1], [0]])
B = np.array([[0], [1]])
Rho_y = sigmay()
A = Qobj(A)
B = Qobj(B)
C = Rho_y * A
D = Rho_y * B
print(C)
print(D)

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.+0.j]
 [0.+1.j]]
Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.-1.j]
 [0.+0.j]]


The preceding code snippet uses the qutip and numpy Python modules to demonstrate
the application of the Y gate to two vectors, A and B, and the results of these operations are
given as C and D, respectively.

The Python code for implementing the identity gate is shown as follows:

In [ ]:
#Identity gate
def IDTY(a):
 if a == 0:
   return 0
 else:
   return 1
if __name__ == '__main__':
 print(IDTY(0))
 print(IDTY(1))

0
1


As can be seen from the preceding code, after defining the function that can be used
to represent the identity, the output is derived from the Identity gate when the inputs
are 0 and 1, respectively.

The python code for Hadamard gate as follows:

In [ ]:
A = np.array([[1], [0]])
B = np.array([[0], [1]])
A = Qobj(A)
B = Qobj(B)
H_matrix=1/np.sqrt(2)*np.array([[1, 1],
                                [1,-1]])
C = H_matrix * A
D = H_matrix * B
print(C)
print(D)

[[0.70710678+0.j]
 [0.70710678+0.j]]
[[ 0.70710678+0.j]
 [-0.70710678+0.j]]


The Python code for implementing the NOT gate is shown as follows:

In [ ]:
#NOT gate
def NOT(a):
 if a == 0:
  return 1
 else:
  return 0
if __name__ == '__main__':
 print(NOT(0))
 print(NOT(1))

1
0


The Python code for the OR gate is shown as follows:

In [ ]:
#OR gate
def OR(a,b):
 if a == 0 and b == 0:
  return 0
 else:
  return 1
if __name__ == '__main__':
 print(OR(0,0))
 print(OR(0,1))
 print(OR(1,0))
 print(OR(1,1))

0
1
1
1


The Python code for the AND gate is given as follows:

In [ ]:
#AND gate
def AND(a,b):
 if a == 1 and b == 1:
  return 1
 else:
  return 0
if __name__ == '__main__':
 print(AND(0,0))
 print(AND(0,1))
 print(AND(1,0))
 print(AND(1,1))

0
0
0
1


The Python code for the XOR gate is given here:

In [ ]:
#XOR gate
def XOR(a,b):
  if a != b:
   return 1
  else:
   return 0
if __name__ == '__main__':
  print(XOR(0,0))
  print(XOR(0,1))
  print(XOR(1,0))
  print(XOR(1,1))

0
1
1
0


The Python code for the NOR gate is given as follows:

In [ ]:
#NOR gate
def NOR(a,b):
  if a == 0 and b == 0:
   return 1
  else:
   return 0
if __name__ == '__main__':
 print(NOR(0,0))
 print(NOR(0,1))
 print(NOR(1,0))
 print(NOR(1,1))

1
0
0
0


The python code for NAND gate as follows:

In [ ]:
#NAND gate
def NAND(a,b):
  if a == 1 and b == 1:
   return 0
  else:
   return 1
if __name__ == '__main__':
 print(NAND(0,0))
 print(NAND(0,1))
 print(NAND(1,0))
 print(NAND(1,1))

1
1
1
0
